# 将函数作为返回值
```python
def lazy_sum(*args):
    def sum():
        ax = 0
        for n in args:
            ax = ax + n
        return ax
    return sum
f = lazy_sum(1, 3, 5, 7, 9)
f() # 25
```

# 闭包
当一个函数返回了一个函数后，其内部的局部变量还被新函数引用

需要注意

```python
def count():
    fs = []
    for i in range(1, 4):
        def f():
             # 下方结果都是9的原因是，此处的i并没有立即被执行
             # 当等到函数返回时，它们所引用的变量i已经变为3了
             return i*i
        fs.append(f)
    return fs

f1, f2, f3 = count()
f1() # 9
f2() # 9
f3() # 9
```

解决上述问题

```python
def count():
    fs = []
    def f(i):
        # 多定义一个函数
        def g():
            return i * i
        return g

    for i in range(1, 4):
        # 使得变量在调用函数时立马被使用
        fs.append(f(i))
    return fs
```

# nonlocal
使用闭包就是内层函数访问了外层函数的局部变量，如果只是读外部变量的值，那么闭包函数调用正常：
```python
def inc():
    x = 0
    def fn():
        # 仅读取x的值:
        return x + 1
    return fn

f = inc()
print(f()) # 1
print(f()) # 1
```

如果对外层变量赋值，python解释器会把`x`当做函数`fn()`的局部变量，会报错:   

原因是`x`作为局部变量并没有初始化，直接计算`x+1`是不行的。但我们其实是想引用`inc()`函数内部的`x`，所以需要在`fn()`函数内部加一个`nonlocal x`的声明。加上这个声明后，解释器把`fn()`的`x`看作外层函数的局部变量，它已经被初始化了，可以正确计算`x+1`。
```python
def inc():
    x = 0
    def fn():
        # nonlocal x
        x = x + 1
        return x
    return fn

f = inc()
print(f()) # 1
print(f()) # 2
```